/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author nanon
 */
public class AddEngineerForm extends javax.swing.JFrame {

    /**
     * Creates new form AddEngineerForm
     */
    String gender;
    String role;
    
    public AddEngineerForm() {
        initComponents();
        this .setExtendedState(MAXIMIZED_BOTH);
        photo.setSize(1980, 1080);
        this.setSize(1980, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        whours = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("First name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 180, 490, 60);

        fname.setBackground(new java.awt.Color(204, 204, 255));
        fname.setForeground(new java.awt.Color(0, 0, 51));
        fname.setText(" ");
        getContentPane().add(fname);
        fname.setBounds(1040, 200, 370, 22);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Sur name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 250, 470, 60);

        lname.setBackground(new java.awt.Color(204, 204, 255));
        lname.setForeground(new java.awt.Color(0, 0, 51));
        lname.setText(" ");
        getContentPane().add(lname);
        lname.setBounds(1040, 270, 370, 22);

        Gender.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 204));
        Gender.setText("Gender");
        getContentPane().add(Gender);
        Gender.setBounds(530, 320, 250, 60);

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(1050, 330, 55, 25);

        buttonGroup1.add(female);
        female.setText("Female");
        getContentPane().add(female);
        female.setBounds(1140, 330, 71, 25);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 370, 150, 90);

        age.setBackground(new java.awt.Color(204, 204, 255));
        age.setForeground(new java.awt.Color(51, 0, 51));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(1050, 410, 370, 22);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 450, 190, 70);

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(email);
        email.setBounds(1050, 470, 370, 22);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 530, 360, 60);

        password.setBackground(new java.awt.Color(204, 204, 255));
        password.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(password);
        password.setBounds(1050, 540, 370, 22);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Working Hours");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 590, 450, 80);

        whours.setBackground(new java.awt.Color(204, 204, 255));
        whours.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(whours);
        whours.setBounds(1050, 620, 370, 22);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Position");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 680, 310, 60);

        position.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        position.setForeground(new java.awt.Color(102, 102, 0));
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Team Leader", "Software Engineer", "Software Developer", "Web Developer", "Tester", "Security Engineer", " ", " " }));
        getContentPane().add(position);
        position.setBounds(1070, 700, 146, 30);

        addbtn.setBackground(new java.awt.Color(204, 204, 204));
        addbtn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        addbtn.setForeground(new java.awt.Color(102, 102, 0));
        addbtn.setText("ADD Engineer");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn);
        addbtn.setBounds(1210, 750, 320, 40);

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/addpic/mini.jpg"))); // NOI18N
        getContentPane().add(photo);
        photo.setBounds(1, -14, 1210, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=employee_system;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String fun="insert into engineer (fname,lname,gender,age,email,salary,password,workinghours,position) values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(fun);
            pst.setString(1,fname.getText());
            pst.setString(2,lname.getText());
            if(male.isSelected())
            {
                gender="male";
            }
            if(female.isSelected())
            {
                gender="female";
            }
            pst.setString(3,gender);
            pst.setInt(4,Integer.valueOf(age.getText()));
            pst.setString(5,email.getText());
            pst.setString(7,password.getText());
            pst.setInt(8,Integer.valueOf(whours.getText()));
            
            role=position.getSelectedItem().toString();
            pst.setString(9,role);
             Grade g=new Grade(role);
              double d=g.calculate_salary(role, Integer.valueOf(whours.getText()));
          
          Employee e=new Engineer(fname.getText(),lname.getText(),gender,email.getText(),Integer.valueOf(age.getText()),password.getText(),
                Integer.valueOf(whours.getText()),role,d  );
         // Grade g=new Grade(role);
         // g.calculate_salary(role, Integer.valueOf(whours.getText()));
          float ff=g.calculate_salary(role, Integer.valueOf(whours.getText()));
          
          pst.setFloat(6,ff);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Added successfully");
            new Admin().setVisible(true);
            this.setVisible(false);
            
        }
        
       
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEngineerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField password;
    private javax.swing.JLabel photo;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField whours;
    // End of variables declaration//GEN-END:variables
}
