/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;

/**
 *
 * @author nanon
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this .setExtendedState(MAXIMIZED_BOTH);
        photo.setSize(1980, 1080);
        this.setSize(1980, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addemployee = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        deleteEngineer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addTrainee = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addemployee.setBackground(new java.awt.Color(204, 204, 255));
        addemployee.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        addemployee.setForeground(new java.awt.Color(0, 51, 51));
        addemployee.setText("Add Engineer");
        addemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemployeeActionPerformed(evt);
            }
        });
        getContentPane().add(addemployee);
        addemployee.setBounds(470, 270, 360, 60);

        edit.setBackground(new java.awt.Color(204, 204, 255));
        edit.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 51, 51));
        edit.setText("Edit Engineer");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(470, 590, 360, 50);

        deleteEngineer.setBackground(new java.awt.Color(204, 204, 255));
        deleteEngineer.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        deleteEngineer.setForeground(new java.awt.Color(0, 51, 51));
        deleteEngineer.setText("Delete Engineer");
        deleteEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEngineerActionPerformed(evt);
            }
        });
        getContentPane().add(deleteEngineer);
        deleteEngineer.setBounds(470, 430, 360, 60);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Show Engineers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 750, 360, 60);

        addTrainee.setBackground(new java.awt.Color(204, 204, 255));
        addTrainee.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        addTrainee.setForeground(new java.awt.Color(0, 51, 51));
        addTrainee.setText("Add Trainee");
        addTrainee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTraineeActionPerformed(evt);
            }
        });
        getContentPane().add(addTrainee);
        addTrainee.setBounds(1140, 270, 330, 60);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Edit Trainee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1140, 590, 330, 60);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Delete Trainee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1140, 430, 330, 60);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("Show Trainee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1140, 750, 330, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Designed by Code Makers 2019.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1180, 900, 240, 17);

        photo.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanon\\Desktop\\hi2.jpg")); // NOI18N
        getContentPane().add(photo);
        photo.setBounds(0, -30, 1460, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemployeeActionPerformed
        
         AddEngineerForm addengineer=new AddEngineerForm();
         addengineer.setVisible(true);
         setVisible(false);
         
         
    }//GEN-LAST:event_addemployeeActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        EditEngineerForm editengineer=new EditEngineerForm();
        editengineer.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_editActionPerformed

    private void deleteEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEngineerActionPerformed
        // TODO add your handling code here:
        DeleteEngineerForm delengineer=new DeleteEngineerForm();
         delengineer.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_deleteEngineerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ShowEngineersForm showngineer=new ShowEngineersForm();
         showngineer.setVisible(true);
         setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addTraineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTraineeActionPerformed
        // TODO add your handling code here:
         AddTraineeForm showngineer=new AddTraineeForm();
         showngineer.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_addTraineeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EditTraineeForm showngineer=new EditTraineeForm();
         showngineer.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DeleteTraineeForm showngineer=new DeleteTraineeForm();
         showngineer.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ShowTraineeForm showTrainee=new ShowTraineeForm();
         showTrainee.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrainee;
    private javax.swing.JButton addemployee;
    private javax.swing.JButton deleteEngineer;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
