/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author nanon
 */
public class DeleteEngineerForm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEngineerForm
     */
    public DeleteEngineerForm() {
        initComponents();
        this .setExtendedState(MAXIMIZED_BOTH);
        photo.setSize(1980, 1080);
        this.setSize(1980, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        whours = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Engineer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(930, 160, 450, 120);

        id.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(id);
        id.setBounds(1410, 220, 320, 20);

        search.setBackground(new java.awt.Color(204, 204, 255));
        search.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        search.setForeground(new java.awt.Color(0, 51, 51));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(1630, 800, 220, 50);

        whours.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(whours);
        whours.setBounds(1410, 670, 320, 20);

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(920, 460, 260, 120);

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 0));
        jLabel8.setText("Position");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(930, 690, 380, 120);

        email.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(email);
        email.setBounds(1410, 520, 320, 20);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("First name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(930, 260, 410, 80);

        position.setBackground(new java.awt.Color(204, 204, 255));
        position.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        position.setForeground(new java.awt.Color(0, 51, 51));
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Team Leader", "Software Engineer", "Software Developer", "Web Developer", "Tester", "Security Engineer", " ", " " }));
        getContentPane().add(position);
        position.setBounds(1410, 750, 200, 30);

        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(920, 530, 380, 120);

        fname.setBackground(new java.awt.Color(204, 255, 204));
        fname.setText(" ");
        getContentPane().add(fname);
        fname.setBounds(1410, 300, 320, 20);

        password.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(password);
        password.setBounds(1410, 590, 320, 20);

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(920, 390, 250, 120);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("Sur name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(920, 320, 400, 120);

        age.setBackground(new java.awt.Color(204, 255, 204));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(1410, 450, 320, 20);

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("Work Hours");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(910, 640, 580, 60);

        lname.setBackground(new java.awt.Color(204, 255, 204));
        lname.setText(" ");
        getContentPane().add(lname);
        lname.setBounds(1410, 380, 320, 20);

        delete.setBackground(new java.awt.Color(204, 204, 255));
        delete.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 51, 51));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1350, 800, 220, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("Designed by Code Makers 2019.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1340, 960, 250, 30);

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/addpic/anaa.jpg"))); // NOI18N
        getContentPane().add(photo);
        photo.setBounds(1, -4, 1600, 1220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       boolean found =false;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=employee_system;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            int i=Integer.valueOf(id.getText());
            String query="Select * FROM engineer WhERE ID="+i;
            PreparedStatement pst=con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
    
            while(rs.next())
            {
                fname.setText(rs.getString("fname"));
                lname.setText(rs.getString("lname"));
                age.setText(rs.getString("Age"));
                email.setText(rs.getString("email"));
                password.setText(rs.getString("password"));
                whours.setText(rs.getString("workinghours"));
                position.setSelectedItem(rs.getString("position"));
                found=true;
            }
          if(!found)
           {
               JOptionPane.showMessageDialog(null, "ID NOT FOUND!");
           }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=employee_system;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            int i=Integer.valueOf(id.getText());
            String query="Delete FROM engineer WhERE ID="+i;
            PreparedStatement pst=con.prepareStatement(query);
           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted successfully");
           new Admin().setVisible(true);
            this.setVisible(false);
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEngineerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField password;
    private javax.swing.JLabel photo;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JButton search;
    private javax.swing.JTextField whours;
    // End of variables declaration//GEN-END:variables
}
