/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nanon
 */
public class ShowTraineeForm extends javax.swing.JFrame {

    /**
     * Creates new form ShowTraineeForm
     */
    public ShowTraineeForm() {
        initComponents();
        show_user();
        this .setExtendedState(MAXIMIZED_BOTH);
        this.setSize(1980, 1080);
    }
public ArrayList<Trainee>traList()
{
    ArrayList<Trainee>traList=new ArrayList<Trainee>();
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=employee_system;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String query="SELECT * FROM trainee";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query);
            Trainee tra;
            while(rs.next()){
                //double GPA, String University, int AcademicYear,String FirstName, String SurName, String Gender, String Email, int Age,  String Password,double salary
                tra=new Trainee(rs.getFloat("GPA"),rs.getString("university"),rs.getInt("academicyear"),rs.getString("fname"),rs.getString("lname"),rs.getString("gender"),rs.getString("email"),rs.getInt("age"),rs.getString("password"),rs.getFloat("salary") );
                traList.add(tra);
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         return traList;
}
public void show_user(){
        ArrayList<Trainee> list = traList();
        DefaultTableModel model = (DefaultTableModel)TraineeTable.getModel();
        Object[] row = new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getFirstName();
            row[1]=list.get(i).getSurName();
            row[2]=list.get(i).getGender();
            row[3]=list.get(i).getAge();
            row[4]=list.get(i).getEmail();
            row[5]=list.get(i).getPassword();
            row[6]=list.get(i).getUniversity();
            row[7]=list.get(i).getAcademicYear();
            row[8]=list.get(i).getGPA();
            row[9]=list.get(i).getSalary();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TraineeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TraineeTable.setBackground(new java.awt.Color(204, 204, 255));
        TraineeTable.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/addpic/admin.jpg")))); // NOI18N
        TraineeTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TraineeTable.setForeground(new java.awt.Color(51, 51, 0));
        TraineeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Age", "Email", "Password", "University", "Academic Year", "GPA", "Salary"
            }
        ));
        jScrollPane1.setViewportView(TraineeTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1970, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTraineeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTraineeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTraineeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTraineeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowTraineeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TraineeTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
