/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanon
 */
public class ShowEngineersForm extends javax.swing.JFrame {

    /**
     * Creates new form ShowEngineersForm
     */
    public ShowEngineersForm() {
        initComponents();
         show_user();
         this .setExtendedState(MAXIMIZED_BOTH);
        this.setSize(1980, 1080);
    }
public ArrayList<Engineer>engList()
{
    ArrayList<Engineer>engList=new ArrayList<Engineer>();
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=employee_system;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String query="SELECT * FROM engineer";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query);
            Engineer eng;
            while(rs.next()){
                eng=new Engineer( rs.getString("fname"), rs.getString("lname"), rs.getString("gender"), rs.getString("email"), rs.getInt("age"),rs.getString("password"), rs.getInt("workinghours"), rs.getString("position"),rs.getDouble("salary"));
                engList.add(eng);
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         return engList;
}
  public void show_user(){
        ArrayList<Engineer> list = engList();
        DefaultTableModel model = (DefaultTableModel)EngineerTable.getModel();
        Object[] row = new Object[9];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getFirstName();
            row[1]=list.get(i).getSurName();
            row[2]=list.get(i).getGender();
            row[3]=list.get(i).getAge();
            row[4]=list.get(i).getEmail();
            row[5]=list.get(i).getPassword();
            row[6]=list.get(i).getPosition();
            row[7]=list.get(i).getWorkingHors();
            row[8]=list.get(i).getSalary();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EngineerTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        EngineerTable.setBackground(new java.awt.Color(204, 204, 255));
        EngineerTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        EngineerTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        EngineerTable.setForeground(new java.awt.Color(51, 51, 0));
        EngineerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Age", "Email", "Password", "Position", "Worling Hours", "Salary"
            }
        ));
        jScrollPane1.setViewportView(EngineerTable);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowEngineersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowEngineersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowEngineersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowEngineersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowEngineersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EngineerTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
